config/routes.rb
Rails.application.routes.draw do

  get "signup" => 'users#new'

  root 'welcome#home'

    resources :users

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:fname])
  end

  def new
  	@user = User.new
  end

  def create
 			@user = User.new(params[:user])
 		if @user.save

	 		flash[:notice] = "Your account was created
			successfully."
			# redirect_to user_path @user
			redirect_to users_path
 		else
		 	flash[:alert] = "There was a problem saving your
		 	account."
		 	redirect_to new_user_path
 		end
	end

	def show
		@user = User.find(params [:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dawnapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<%= yield %>

<% flash[:notice] if flash[:notice] %>
	<% flash[:alert] if flash[:alert] %>
	



</body>
</html>

app/views/users/index.html.erb
 <div class="shadow2">
	<div class="shadow1">

		<h1> DawnApp Users</h1>



		<% @users.each do |user| %>
			<strong><%= user.fname %></strong>
			<strong><%= user.lname %><strong><br>
			<%= user.email %><hr><br>
			<% end %>

			<button><%= link_to 'Sign up new users...', signup_path %></button>

	</div>
</div>

app/views/users/new.html.erb
	<div class="shadow2">
		<div class="shadow1">

			<h1> DawnApp Users</h1>
			
					
		<%= form_for @user do |f| %>
		 
		  <%= f.label :fname %><br> 
		  <%= f.text_field :fname %><br><hr>

		  <%= f.label :lname %><br>
		  <%= f.text_field :lname %><br><hr>
		 
		  <%= f.label :email %><br>
		  <%= f.email_field :email %><br><hr>
		 
		  <%= f.label :password %><br>
		  <%= f.password_field :password %><br><hr>

		 
		  <button id="b"><%= f.submit "Create" %></button>
		 
			<% end %>

	
	</div>
</div>

app/views/users/show.html.erb
<h1>...under contruction <h1>



<h1><%= user.fname %><h1>

app/views/welcome/home.html.erb
<h1>Welcome to DawnApp</h1>

<h4>Go to all users....</h4><br>

<button><h4><%= link_to 'Click Here', users_path %><h4></button>